services:
  db:
    image: postgres
    container_name: postgres-database
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: bobert
      POSTGRES_PASSWORD: password
    ports:
      - "5432":"5432"

  workbench:
    image: dpage/pgadmin4
    container_name: postgresql-workbench
    ports:
      - "5000":"80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    depends_on:
      - db
    secrets:
      - pgadmin_password

volumes:
  postgres-data:

secrets:
  pgadmin_password:
    file: ./pgadmin_password.txt